"""macOS build script — creates VAYU.app and VAYU.dmg

Usage (on macOS):
    python packaging/build_mac.py          — build .app with py2app
    python packaging/build_mac.py --dmg    — build .app + create .dmg
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def build_app():
    root = _project_root()
    dist = root / "dist"
    build_dir = root / "build"

    print("[macOS Build] Cleaning previous builds...")
    for d in [dist, build_dir]:
        if d.exists():
            shutil.rmtree(d)

    # Ensure py2app is installed
    try:
        import py2app  # noqa
    except ImportError:
        print("[macOS Build] Installing py2app...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "py2app"],
            check=True, cwd=str(root)
        )

    print("[macOS Build] Creating setup.py for py2app...")
    setup_path = root / "setup_mac.py"
    setup_path.write_text(f'''"""
Py2app setup script for VAYU macOS build.
Auto-generated by packaging/build_mac.py
"""

import sys
from setuptools import setup

APP = ["main.py"]
DATA_FOLDERS = ["core", "config", "memory", "actions", "brain", "voice", "vision", "plugins"]

OPTIONS = {{
    "argv_emulation": False,
    "includes": [
        "PyQt6",
        "google",
        "PIL",
        "numpy",
        "sounddevice",
        "edge_tts",
        "qrcode",
        "requests",
        "json",
        "pathlib",
    ],
    "excludes": [
        "torch",
        "scipy",
        "pandas",
        "matplotlib",
        "tensorboard",
        "PyQt5",
    ],
    "iconfile": "icon.icns" if (Path(__file__).parent / "icon.icns").exists() else None,
    "plist": {{
        "CFBundleName": "VAYU",
        "CFBundleDisplayName": "VAYU AI Assistant",
        "CFBundleIdentifier": "com.purveshbhadale.vayu",
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleExecutable": "VAYU",
        "NSHighResolutionCapable": True,
        "NSRequiresAquaSystemAppearance": False,
    }},
    "packages": ["PyQt6", "PIL", "numpy"],
    "site_packages": True,
    "resources": DATA_FOLDERS,
}}

setup(
    name="VAYU",
    app=APP,
    options={{"py2app": OPTIONS}},
    setup_requires=["py2app"],
)
''')

    print("[macOS Build] Running py2app...")
    result = subprocess.run(
        [sys.executable, "setup_mac.py", "py2app"],
        cwd=str(root)
    )
    if result.returncode != 0:
        print("[macOS Build] py2app failed!")
        return False

    # Rename .app if needed and copy data folders inside
    app_path = dist / "VAYU.app"
    if not app_path.exists():
        # py2app sometimes uses main.app
        main_app = dist / "main.app"
        if main_app.exists():
            main_app.rename(app_path)

    # Bundle data folders into the .app bundle
    if app_path.exists():
        print("[macOS Build] Bundling data folders into .app...")
        resources = app_path / "Contents" / "Resources"
        for folder in ["core", "config", "memory", "actions", "brain", "voice", "vision", "plugins"]:
            src = root / folder
            dst = resources / folder
            if src.exists() and not dst.exists():
                shutil.copytree(src, dst, symlinks=True)
                print(f"  Copied {folder}/")

    print(f"[macOS Build] App bundle created: {app_path}")
    return True


def create_dmg():
    root = _project_root()
    dist = root / "dist"
    app_path = dist / "VAYU.app"

    if not app_path.exists():
        print("[macOS Build] Build the .app first: python packaging/build_mac.py")
        return False

    # Check for create-dmg (Homebrew tool)
    dmg_path = dist / "VAYU.dmg"

    # Try create-dmg first (cleanest result)
    try:
        subprocess.run(["which", "create-dmg"], check=True, capture_output=True)
        print("[macOS Build] Using create-dmg...")
        # Remove existing dmg
        if dmg_path.exists():
            dmg_path.unlink()

        result = subprocess.run([
            "create-dmg",
            "--volname", "VAYU",
            "--volicon", str(root / "icon.icns") if (root / "icon.icns").exists() else None,
            "--window-pos", "200", "200",
            "--window-size", "600", "400",
            "--icon-size", "100",
            "--icon", "VAYU.app", "200", "170",
            "--app-drop-link", "400", "170",
            str(dmg_path),
            str(app_path),
        ], cwd=str(dist))
        if result.returncode != 0:
            raise subprocess.CalledProcessError(result.returncode, "create-dmg")

    except (subprocess.CalledProcessError, FileNotFoundError):
        # Fallback: use hdiutil (built-in on macOS)
        print("[macOS Build] create-dmg not found, using hdiutil...")
        temp_dmg = dist / "VAYU_temp.dmg"
        if temp_dmg.exists():
            temp_dmg.unlink()

        # Create a temporary DMG with a symlink to /Applications
        subprocess.run([
            "hdiutil", "create",
            "-srcfolder", str(app_path),
            "-volname", "VAYU",
            "-fs", "HFS+",
            "-format", "UDRW",
            str(temp_dmg),
        ], check=True, cwd=str(dist))

        # Convert to compressed DMG
        if dmg_path.exists():
            dmg_path.unlink()
        subprocess.run([
            "hdiutil", "convert",
            str(temp_dmg),
            "-format", "UDZO",
            "-o", str(dmg_path),
        ], check=True, cwd=str(dist))

        temp_dmg.unlink(missing_ok=True)

    # Clean up build artifacts
    build_dir = root / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)

    setup_py = root / "setup_mac.py"
    if setup_py.exists():
        setup_py.unlink()

    size_mb = dmg_path.stat().st_size / (1024 * 1024)
    print(f"[macOS Build] DMG created: {dmg_path} ({size_mb:.0f} MB)")
    return True


def copy_to_website():
    root = _project_root()
    dmg_path = root / "dist" / "VAYU.dmg"
    website_dmg = root / "website" / "downloads" / "VAYU.dmg"

    if not dmg_path.exists():
        print("[macOS Build] No DMG found to copy.")
        return False

    website_dmg.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(dmg_path, website_dmg)
    size_mb = website_dmg.stat().st_size / (1024 * 1024)
    print(f"[macOS Build] Copied to website/downloads/VAYU.dmg ({size_mb:.0f} MB)")
    return True


if __name__ == "__main__":
    if "--dmg" in sys.argv:
        if build_app():
            create_dmg()
            copy_to_website()
    else:
        build_app()
